@extends('adminlte::page')
@section('title', 'Motivos de Cambio')
@section('css')<link rel="stylesheet" href="{{ asset('css/rsu.css') }}?v={{ filemtime(public_path('css/rsu.css')) }}">@stop
@section('content_header')
<div class="d-flex justify-content-between align-items-center"><h1 class="rsu-page-title"><i class="fas fa-clipboard-list"></i> Lista de Motivos</h1><button class="btn btn-primary" data-toggle="modal" data-target="#createMotivoCambioModal"><i class="fas fa-plus mr-1"></i> Nuevo Motivo</button></div>
@stop
@section('content')
<div class="js-crud-container"><div class="js-flash-messages">@include('partials.alerts')</div><div class="card"><div class="card-body">
<div class="d-flex justify-content-between flex-wrap mb-3">
{!! Form::open(['route'=>'motivos-cambio.index','method'=>'GET','class'=>'form-inline mb-2']) !!}<span class="mr-2">Mostrar</span>{!! Form::select('per_page',[10=>10,25=>25,50=>50],request('per_page',10),['class'=>'custom-select custom-select-sm','onchange'=>'this.form.submit()']) !!}<span class="ml-2">registros</span>{!! Form::hidden('q',request('q')) !!}{!! Form::close() !!}
{!! Form::open(['route'=>'motivos-cambio.index','method'=>'GET','class'=>'form-inline mb-2']) !!}{!! Form::hidden('per_page',request('per_page',10)) !!}{!! Form::label('q','Buscar:',['class'=>'mr-2']) !!}{!! Form::text('q',request('q'),['class'=>'form-control form-control-sm']) !!}{!! Form::close() !!}
</div>
<div class="table-responsive"><table class="table table-striped table-hover"><thead><tr><th>Nombre</th><th>Descripción</th><th>Estado</th><th>Creación</th><th class="text-center">Acciones</th></tr></thead><tbody>
@forelse($reasons as $reason)<tr><td class="font-weight-bold">{{ $reason->name }}</td><td>{{ $reason->descripcion ?: '-' }}</td><td><span class="badge {{ $reason->activo ? 'badge-success':'badge-secondary' }}">{{ $reason->activo ? 'Activo':'Inactivo' }}</span></td><td>{{ $reason->created_at->format('d/m/Y H:i') }}</td><td class="text-center text-nowrap"><button class="btn btn-warning btn-sm" data-toggle="modal" data-target="#editMotivoCambioModal{{ $reason->id }}"><i class="fas fa-edit"></i></button> {!! Form::open(['route'=>['motivos-cambio.destroy',$reason],'method'=>'DELETE','class'=>'d-inline js-ajax-form','data-confirm'=>'¿Deseas eliminar este motivo?']) !!}<button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>{!! Form::close() !!}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">No hay motivos registrados.</td></tr>@endforelse
</tbody></table></div><div class="rsu-table-footer"><span>Mostrando {{ $reasons->firstItem() ?? 0 }} a {{ $reasons->lastItem() ?? 0 }} de {{ $reasons->total() }} registros</span>{{ $reasons->links() }}</div></div></div>
<div class="modal fade" id="createMotivoCambioModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content">{!! Form::open(['route'=>'motivos-cambio.store','method'=>'POST','class'=>'js-ajax-form']) !!}<div class="modal-header bg-primary"><h5 class="modal-title"><i class="fas fa-clipboard-list mr-1"></i> Nuevo Motivo</h5><button type="button" class="close text-white" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><div class="form-group">{!! Form::label('name','Nombre *') !!}{!! Form::text('name',null,['class'=>'form-control','required'=>true,'maxlength'=>120]) !!}</div><div class="form-group">{!! Form::label('descripcion','Descripción') !!}{!! Form::textarea('descripcion',null,['class'=>'form-control','rows'=>3]) !!}</div><input type="hidden" name="activo" value="0"><div class="custom-control custom-switch"><input type="checkbox" class="custom-control-input" id="reasonActiveCreate" name="activo" value="1" checked><label class="custom-control-label text-success font-weight-bold" for="reasonActiveCreate">Activo</label></div></div><div class="modal-footer"><button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times mr-1"></i> Cancelar</button><button type="submit" class="btn btn-primary"><i class="fas fa-save mr-1"></i> Guardar</button></div>{!! Form::close() !!}</div></div></div>
@foreach($reasons as $reason)<div class="modal fade" id="editMotivoCambioModal{{ $reason->id }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content">{!! Form::model($reason,['route'=>['motivos-cambio.update',$reason],'method'=>'PUT','class'=>'js-ajax-form']) !!}<div class="modal-header bg-primary"><h5 class="modal-title"><i class="fas fa-clipboard-list mr-1"></i> Editar Motivo</h5><button type="button" class="close text-white" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><div class="form-group">{!! Form::label('name','Nombre *') !!}{!! Form::text('name',null,['class'=>'form-control','required'=>true,'maxlength'=>120]) !!}</div><div class="form-group">{!! Form::label('descripcion','Descripción') !!}{!! Form::textarea('descripcion',null,['class'=>'form-control','rows'=>3]) !!}</div><input type="hidden" name="activo" value="0"><div class="custom-control custom-switch"><input type="checkbox" class="custom-control-input" id="reasonActive{{ $reason->id }}" name="activo" value="1" @checked($reason->activo)><label class="custom-control-label text-success font-weight-bold" for="reasonActive{{ $reason->id }}">Activo</label></div></div><div class="modal-footer"><button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times mr-1"></i> Cancelar</button><button type="submit" class="btn btn-primary"><i class="fas fa-save mr-1"></i> Guardar</button></div>{!! Form::close() !!}</div></div></div>@endforeach
</div>
@stop
@section('js')<script src="{{ asset('js/rsu-crud.js') }}?v={{ filemtime(public_path('js/rsu-crud.js')) }}"></script>@stop